spring.application.name=private-expense-tracker-backend

# Database
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail
spring.mail.from=${EMAIL_FROM}

# Server
server.port=${SERVER_PORT:8080}

# JWT ? no default secret, must be set via environment variable in production
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# OTP
app.otp.expiry-minutes=${OTP_EXPIRY_MINUTES:5}
app.otp.resend-cooldown-seconds=${OTP_RESEND_COOLDOWN_SECONDS:60}
app.otp.max-attempts=${OTP_MAX_ATTEMPTS:3}

# App
app.base-url=${BASE_URL}

app.brevo.api-key=${BREVO_API_KEY}

# deployment test